name: joegondek
favicon: null
layout_spectrum: 0.00010871514678001404
typography_spectrum: 0.07860500388778746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.12238577310927212
  lightness: 0.45168065442703664
  saturation: 0.7413997102994472
  rhythmicContrast: 0.4588471173774451
purpose: []
